#!/bin/bash
PURPLE='\033[0;35m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'


for i in $(ls chekers/$1/);do
    echo -ne "${PURPLE}$i:${NC}"
    ./checker.bash ./a.out ./chekers/$1/$i
    echo -e "${BLUE}\n--------------------------------------------------${NC}"
done
