#!/bin/bash
PURPLE='\033[0;35m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'
for n in $(ls /home/imadovetch/simple_shell/chekers/ | sort -n );do
echo "$n"
for i in $(ls chekers/$n/);do

 echo -ne "${PURPLE}$i:${NC}"
    ./checker.bash ./a.out ./chekers/$n/$i
    echo -e "${BLUE}\n--------------------------------------------------\n\n${NC}"
done
done